version: '3.8'

name: swarmica

volumes:
  postgres_data:
  static_value:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../library/library/.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    depends_on:
      - db
    env_file:
      - ../library/library/.env
    volumes:
      - ../library:/code
      - static_value:/code/static/

  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
